import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import PageTransition from "@/components/page-transition";
import TransitionEffect from "@/components/transition-effect";

const jetbrains = Poppins({ 
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetbrains.className}>
        <Header />
        <TransitionEffect/>
        <PageTransition>
          <main className="mt-16">
            {children}
          </main>
        </PageTransition>
      </body>
    </html>
  );
}
